name: pi2
version: 16.04-0.17
summary: Raspberry Pi 2 support package
description: |
 Support files for booting Raspberry Pi
type: gadget
architectures:
  - armhf
confinement: strict
slots:
  boot-config-slot:
    interface: boot-config
grade: stable
parts:
    prebuilt:
        plugin: dump
        source: prebuilt
    hooks:
        plugin: dump
        source: prebuild-meta
    licenses:
        plugin: copy
        files:
            COPYING.linux: .
            LICENCE.broadcom: .
            LICENSE.oracle: .
